name: CI & Docker Publish

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        if: github.ref == 'refs/heads/main'
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-k8s-demo:latest
          docker build -t $IMAGE .
          docker push $IMAGE
